### ISSUE TITLE
CCT and CRI calculations for Spectral-Workbench

### ISSUE THREAD

**Issue by Tom11Films** [jywarren/spectral-workbench#115]
CCT (correlated color tempeture) and CRI (Color rendering index) would be very useful to know for an existing light source.  It should be possible to calculate them from the spectrograph of a white light.  Here are several URLS with more information on the formulas:

http://en.wikipedia.org/wiki/Color_rendering_index
http://en.wikipedia.org/wiki/Correlated_color_temperature#Correlated_color_temperature

http://www.kruschwitz.com/cri.htm
http://www.efg2.com/Lab/Graphics/Colors/Chromaticity.htm

**Comment by jywarren** [comment]
It'd be so great to get this ported over; perhaps we could make an attempt as part of the Spectral Workbench 2.0 overhaul. I'm going to move this issue over there but keep references: https://github.com/publiclab/spectral-workbench/issues/59
