### ISSUE TITLE
Toggles on Charts don't Un-toggle

### ISSUE THREAD

**Issue by samjacoby** [jywarren/spectral-workbench#130]
Not really a bug, but worth noting -- in the JS charts interface, 'Show wavenumber', 'Hide legend', and 'Toggle units' are one way -- they do not reverse on repeated pressed. 'Toggle RGB', however, does, and restores state, allowing you to toggle the other options again.

Google Chrome Version 21.0.1180.89
OS X 10.6.8

**Comment by jywarren** [comment]
wontfix for now
