### ISSUE TITLE
CSV download should more closely match defacto CSV spectra encoding.

### ISSUE THREAD

**Issue by tclarke** [jywarren/spectral-workbench#136]
Many spectral tools (ENVI, Opticks, etc.) expect reflectance/transmission/emissivity data to be floats the range 0.0-1.0 (or >1.0 for emission spectra) instead of integers. Normalizing to this range should increase the usability of exported spectra.

**Comment by jywarren** [comment]
merging into publiclab/spectral-workbench#4
