### ISSUE TITLE
Include FWHM data in exported spectra

### ISSUE THREAD

**Issue by tclarke** [jywarren/spectral-workbench#137]
The exported spectra (especially the CSV format) should include FWHM values in the third column (or start wavelength/end wavelength in the third and fourth columns). This information can be captured when spectra are uploaded or captured to reflect the precision of the capture hardware. If FWHM isn't available, it can be estimated by using: (where constant is often 1.0)

start = centerWavelength[n-1] - ((centerWavelength[n]  - centerWavelength[n-1] ) * constant) / 2.0;
end = centerWavelength[n-1] - ((centerWavelength[n]  - centerWavelength[n-1] ) * constant) / 2.0;
fwhn = end - start;

**Comment by jywarren** [comment]
merging into https://github.com/publiclab/spectral-workbench/issues/4
