### ISSUE TITLE
Spectrograph not displaying in Internet Explorer 8

### ISSUE THREAD

**Issue by Fastie** [jywarren/spectral-workbench#167]
The spectrograph (the graph of wavelength vs percent) under the image of the spectrum is not displaying in Internet Explorer 8. I didn't notice any other problems in IE8. This bug apparently applies only to IE 8 and below.
![IE8Capture](https://f.cloud.github.com/assets/1805899/60414/b55e00aa-5c0b-11e2-9f9e-bc47c7940bab.JPG)

**Comment by jywarren** [comment]
Given availability of more recent versions of IE, wontfix - does IE9 work?
