### ISSUE TITLE
Non linear calibration

### ISSUE THREAD

**Issue by Fastie** [jywarren/spectral-workbench#187]
It looks like Ebert is capturing images of spectra that are not linear. See this set: http://spectralworkbench.org/sets/show/183. Even though Ebert captures images with the diffraction pattern in the center of the image, there might be some lens distortion, or something else warping the image. Or it could be that the diffraction grating is producing non-linear diffraction patterns.  Whatever the cause, it might be common with this type of spectrometer. To get good calibrations, a non-linear function might have to be applied to spectra.

**Comment by jywarren** [comment]
moving to https://github.com/publiclab/spectral-workbench/issues/55
