### ISSUE TITLE
Sort spectra in a set

### ISSUE THREAD

**Issue by Fastie** [jywarren/spectral-workbench#188]
The display of multiple spectral graphs in a set sometimes benefits from having particular graphs overlain on top of others. E.g., in this set, http://spectralworkbench.org/sets/show/183, no information is lost if the red reference peaks are graphed behind all the other graphs. Currently there does not seem to be any way change the default sorting order, and I have not yet figured out how that order is determined.

**Comment by jywarren** [comment]
Moving to publiclab/spectral-workbench#26
