### ISSUE TITLE
Missing "next page" links

### ISSUE THREAD

**Issue by Fastie** [jywarren/spectral-workbench#191]
Profile page lists 24 of my spectra, but does not have a “next page” link. Any search results page can list 24 spectra, but does not have a “next page” link. Search results page has an unlimited(?) number of “Related sets” (try searching for “test”). “Browse/contributors” and “Browse/Tags” do not have a “next page” link. (is that all of them?)

**Comment by jywarren** [comment]
Closing; this works now, but creating new issue for pagination of user profile sets and contributors and tags at publiclab/spectral-workbench#25
