### ISSUE TITLE
Spectra calibrated with a macro are not listed as calibrated spectra.

### ISSUE THREAD

**Issue by Fastie** [jywarren/spectral-workbench#193]
Spectra calibrated with a macro ($w.calibrate(...)) never show up as a choice for calibrating while uploading or from the analyze page. This means that it is not possible to use some well-calibrated spectra for calibration.  The macro feature offers a workaround, but it would be nice to calibrate on upload using a spectrum carefully calibrated with a macro.

**Comment by jywarren** [comment]
moving to https://github.com/publiclab/spectral-workbench/issues/52
