### ISSUE TITLE
Pixel readout on mouseover

### ISSUE THREAD

**Issue by Fastie** [jywarren/spectral-workbench#198]
This is mentioned in [this issue](https://github.com/jywarren/spectral-workbench/issues/187) but I will repeat it here. There is a readout of nm when the mouse is on the graph of a spectrum on the analyze page. It would be good to also have a readout of pixel distance from the left edge of the spectral image. Then users could glean the information they need to write a macro for calibrating a spectrum.

**Comment by jywarren** [comment]
moving to https://github.com/publiclab/spectral-workbench/issues/56
