### ISSUE TITLE
Spectra in set not aligned properly with each other

### ISSUE THREAD

**Issue by hechtnews** [jywarren/spectral-workbench#204]
I combined two spectra to compare Charles River water fresh from the river, and after a few hours of settling at http://spectralworkbench.org/sets/show/304  . I used the same calibration, and I thought they were aligned with each other when I made the comparison online. But now the set shows the two curves way out of alignment, one offset horizontally by the equivalent of a few hundred nanometers.

**Comment by jywarren** [comment]
Closing, but please reopen if the problem recurs.
