### ISSUE TITLE
installation issues and creating an installation guide

### ISSUE THREAD

**Issue by YvesAD** [jywarren/spectral-workbench#206]
Hello,
(I send this message both on the github "issue page" and via email.)

I am a physics teacher, bought the "desktop" spectrometer from publiclab recently and use spectral workbench for some time now.
 
I want to make a demonstration of spectral workbench in conditions where an internet connection is not available.

So I downloaded the zip from github and i tried to make it run on my old laptop.
I have some problems running the web server version of spectral workbench on a local machine (ubuntu 10.10).

1) I tried the default ruby from ubuntu Maverick.
2) Then replaced it with a 1.9.2 from a ppa.
3) I compiled a ruby 1.9.2  (configure, make, make install)
 (It seems to be a problem of utf8 with 1.9.X)
4) and a 1.8.7. (configure, make, make install)

In every case, I "forced" a version of rails ("sudo gem install -v=2.3.15 rails") as  the "config/environment.rb" is asking for that version. (after testing with the default version.)

I was never able to start spectral workbench.
(The error messages are different from one version of ruby to another. I don't copy them here. The next paragraph will explain why.)

To make it short (at last!), It seems to me the problem is with the gems which are not the exact versions you used.
Is it possible to know the exact configuration you use?
(With someting like RVM maybe?)

I am not a ruby developper but quite an experienced unix/linux system administrator. So maybe this is trivial for a ruby on rails developper but I found the lack of installation documentation really painful!
Is there a document somewhere I missed? Wouldn't it be worth it to create one?

Really hoping for an answer!

Yours.
Yves

--------------------------------------
Yves Delhaye
http://YvesDelhaye.be/

Le binaire divise l'humanité en 10:
Ceux qui le comprennent et les autres.
--------------------------------------

**Comment by jywarren** [comment]
I believe this is vastly improved now that we're on the Rails 3.2 version; closing. Thanks! @YvesAD if you have a chance to try installing the new version, much appreciated! And more improvements are coming with a switch to Bower static asset management.

**Comment by YvesAD** [comment]
Hello,

I'll try a new local install in about two weeks (school holidays then, exam
& reports before!).

Yours
Yves

%%%%%%%%%%%%%%%%%%
http://YvesDelhaye.be
Never believe an atom.
They make up everything!
%%%%%%%%%%%%%%%%%%
