### ISSUE TITLE
Ability to browse full all spectra, not just 5 pages

### ISSUE THREAD

**Issue by NicBr** [jywarren/spectral-workbench#216]
Hi Jeff

I'm not sure, but there may be problem with accessing data & historic files. I was looking for facility to see / compare historic spectral-workbench records...
.
1. Bulk of spectral records seem to be limited to 5 pages?
http://spectralworkbench.org/popular?page=5
http://spectralworkbench.org/dashboard?page=5
.
2. Similar story for Sets, limited to 5 pages?
http://spectralworkbench.org/sets?page=5
.
3. Spectral Workbench contributors seems restricted to 1 page?  http://spectralworkbench.org/contributors
.
Nic

**Comment by jywarren** [comment]
fixed for most links, I believe, others listed now in https://github.com/publiclab/spectral-workbench/issues/25
