### ISSUE TITLE
When hovering over plot line, label isn't highlighted

### ISSUE THREAD

**Issue by nmz787** [jywarren/spectral-workbench#220]
I hover over the grey not-like-the-others plot line here:
http://spectralworkbench.org/sets/show/27

and I can't tell which label it's associated with because the colors are so similar.

Please add some sort of effect that makes the label bold on hover-over, or something noticeable like that.

Also you might consider using different line styles to differentiate data, like dashed hashed or dotted along with the solid already used.

**Comment by jywarren** [comment]
moving this over to https://github.com/publiclab/spectral-workbench/issues/54
