### ISSUE TITLE
Dropdown navigation menu doesn't work on Opera for android

### ISSUE THREAD

**Issue by mathewlippincott** [jywarren/spectral-workbench#228]
the dropdown menu in the upper right corner of the main spectral workbench page doesn't work in Firefox and Opera on Android.

In Firefox, I can tap the menu options and the menu disappears without redirecting to another page.

In Opera, I can't click the options at all, and the menu is treated as "transparent" clicking on content below the menu.

**Comment by jywarren** [comment]
merging into https://github.com/publiclab/spectral-workbench/issues/51
