### ISSUE TITLE
saving/retrieving a calibration

### ISSUE THREAD

**Issue by Adam912** [jywarren/spectral-workbench#243]
HI, I'm using the desktop spectrometer with Firefox.  I can use the calibration routine fine, but the software does not seem to be saving my calibration.  When I save a new spectrum image, it always tells me that this is a new calibration...no cal file names appear in the pulldown.  And when I save a new spectrum, there is no place where I can load the calibration data to overlay on my new spectrum reading.  

Am I missing something?

Also a small quibble:  the software version used in the Calibration tutorial video looks nothing like what's in use now.  Bit confusing for a newbie

**Comment by jywarren** [comment]
We're going to re-do the videos pretty soon, don't worry. Do you mean the pulldown in the capture interface or the analyze interface? 

We're moving all issues to this tracker: https://github.com/publiclab/spectral-workbench/issues/new so if you would please re-open the issue there that would be great.
