### ISSUE TITLE
cannot load such file -- capture_helper

### ISSUE THREAD

**Issue by yellowhuang007** [jywarren/spectral-workbench#245]
I startup the webserver and access it through firefox using the url: http://localhost:3000, and get an error like this:

A source file that the application requires, is missing.

    It is possible that you didn't upload your application files correctly. Please check whether all your application files are uploaded.
    A required library may not installed. Please install all libraries that this application requires.

Further information about the error may have been written to the application's log file. Please check it in order to analyse the problem.

Error message:
    cannot load such file -- capture_helper
Exception class:
    LoadError

It seems like that I lack a library. Does anyone know which library I must install.
Thanks.

**Comment by jywarren** [comment]
Closing this as the main issue seems to be resolved. Thanks!
