### ISSUE TITLE
field of view clipping on high-res smartphone cameras

### ISSUE THREAD

**Issue by ebarry** [jywarren/spectral-workbench#247]
Possible issue with seeing only part of spectrum in mobile spectral workbench. (unconfirmed). 
It may be that some Android cameras are capturing such large images that perhaps spectral workbench is only using part of the camera's field of view. 

![img_3294_github](https://f.cloud.github.com/assets/161439/2467508/22f4c24e-afc0-11e3-84a0-4b4089f674b7.jpg)

**Comment by jywarren** [comment]
moving this to https://github.com/publiclab/spectral-workbench/issues/58; @ebarry can you copy in some more detail like your excellent photo?
