### ISSUE TITLE
hey this is scott

### ISSUE THREAD

**Issue by eustatic** [jywarren/spectral-workbench#251]
i keep getting an error message ("something went wrong") when i try to calibrate.  the error comes as i'm trying to save.  i have windows 7 and chrome. (the latest chrome, i think)

**Comment by jywarren** [comment]
Hmm, can you link to the spectra you were having trouble with? We're cleaning out this issue tracker so if you are still having trouble please open an issue at https://github.com/publiclab/spectral-workbench/issues/new

Thanks!
