### ISSUE TITLE
Feeling stupid

### ISSUE THREAD

**Issue by opticaltest** [jywarren/spectral-workbench#252]
I am a TSM in the optical industry. One of my Optometrist had heard about the DIY Spectrometer and it usefulness in demonstrating the emission of bluelight that comes off computers etc. He bought four and asked me to assemble. Since my husband is very mechanical minded I agreed. We have carefully constructed two of the four units and can not capture a light spectrum even though we are very close to the CFL bulb. We actually only get a black screen. I checked the USB camera and the computer indicates it recognizes the camera and the device is working. Any thoughts???

**Comment by jywarren** [comment]
Hello; could you share any photos of your setup, or links to spectra you've captured? I'm sorry we didn't see this; I hope you contacted the discussion lists at http://publiclab.org/lists for help. I'm closing this as we're moving to a new issue tracker, but if you feel it is a bug, you may file it again at https://github.com/publiclab/spectral-workbench/issues/new
