### ISSUE TITLE
Toggle RGB

### ISSUE THREAD

**Issue by Stoft1** [jywarren/spectral-workbench#258]
Just a small bit -- the initial 'combined' spectral plot is 'white' to differentiate from the RGB plot colors .... but when toggled back, that same plot is 'red' which is likely confusing for most and a bit deceiving (unless you happen to remember the shape of the original combined data. Probably a 5-min fix.

**Comment by jywarren** [comment]
Hi! Can you please copy this over to our new tracker? This tracker is closed and no longer used. Thanks!

https://github.com/publiclab/spectral-workbench/issues

**Comment by jywarren** [comment]
Moved to publiclab/spectral-workbench#109
