### ISSUE TITLE
Calibration Points

### ISSUE THREAD

**Issue by Stoft1** [jywarren/spectral-workbench#259]
The calibration procedure is presently based only on the CFL Blue and Green peaks but because of distortions in the typical detected peak shape, it could be better to include the Red. Also, the procedure instructs the user to find the "highest" green peak. However, the Green peak is actually a double-peak and the highest is not always the "same" peak for all devices -- again, due to peak distortions and general device instability. The instructions should have the user pick the "right-most" peak -- ie. the one on the "red" side of the spectrum with the longer wavelength.

**Comment by jywarren** [comment]
Hi! Can you please copy this over to our new tracker? This tracker is closed and no longer used. Thanks!

https://github.com/publiclab/spectral-workbench/issues

**Comment by jywarren** [comment]
Moved to publiclab/spectral-workbench#110
