### ISSUE TITLE
CSV Data Downloads

### ISSUE THREAD

**Issue by stoltch** [jywarren/spectral-workbench#262]
I am probably missing something but when I select CSV box I go to another screen and no indication of  file info to download. I tried all options for data preferences on the boxes and it was the same thing. Is there a problem downloading data right now? Note: this worked before and I was able to download the data in .csv format then something changed. I tried logging in using Chrome and then Explorer with no change.

Thanks,
Chad

**Comment by jywarren** [comment]
Hi! Can you please copy this over to our new tracker? This tracker is closed and no longer used. Thanks!

https://github.com/publiclab/spectral-workbench/issues

**Comment by jywarren** [comment]
I believe this was fixed in publiclab/spectral-workbench#114
