### ISSUE TITLE
Custom Calibration not available

### ISSUE THREAD

**Issue by rennne** [jywarren/spectral-workbench#263]
As it is stated in the link, it should somehow exist
http://publiclab.org/wiki/spectral-workbench-calibration#Custom+calibrations

but if I click on that link, it does not work.
Since I have Laser-pointers with a know wavelenght, and no CFL available, I would need that option

**Comment by jywarren** [comment]
Hi, sorry if you have done this, but just to check, you have to substitute `SPECTRUM_ID` with the ID # of your spectrum. Did you?

If so, and it didn't work, what did it say when you tried, and with which spectrum did you try it (so we can try to reproduce?)

**Comment by jywarren** [comment]
Closing this - if you re-encounter it please file it at https://github.com/publiclab/spectral-workbench/issues/new, thank you!
